// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: blog_storage_svr.proto

package blog_storage_svr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BlogStorageSvr_SelectCategoryList_FullMethodName = "/blog_storage_svr.blog_storage_svr/SelectCategoryList"
	BlogStorageSvr_GetCategory_FullMethodName        = "/blog_storage_svr.blog_storage_svr/GetCategory"
	BlogStorageSvr_UpdateCategory_FullMethodName     = "/blog_storage_svr.blog_storage_svr/UpdateCategory"
	BlogStorageSvr_CreateCategory_FullMethodName     = "/blog_storage_svr.blog_storage_svr/CreateCategory"
	BlogStorageSvr_SelectTagList_FullMethodName      = "/blog_storage_svr.blog_storage_svr/SelectTagList"
	BlogStorageSvr_GetTag_FullMethodName             = "/blog_storage_svr.blog_storage_svr/GetTag"
	BlogStorageSvr_UpdateTag_FullMethodName          = "/blog_storage_svr.blog_storage_svr/UpdateTag"
	BlogStorageSvr_CreateTag_FullMethodName          = "/blog_storage_svr.blog_storage_svr/CreateTag"
)

// BlogStorageSvrClient is the client API for BlogStorageSvr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlogStorageSvrClient interface {
	SelectCategoryList(ctx context.Context, in *SelectCategoryListReq, opts ...grpc.CallOption) (*SelectCategoryListRsp, error)
	GetCategory(ctx context.Context, in *GetCategoryReq, opts ...grpc.CallOption) (*GetCategoryRsp, error)
	UpdateCategory(ctx context.Context, in *UpdateCategoryReq, opts ...grpc.CallOption) (*UpdateCategoryRsp, error)
	CreateCategory(ctx context.Context, in *CreateCategoryReq, opts ...grpc.CallOption) (*CreateCategoryRsp, error)
	SelectTagList(ctx context.Context, in *SelectTagListReq, opts ...grpc.CallOption) (*SelectTagListRsp, error)
	GetTag(ctx context.Context, in *GetTagReq, opts ...grpc.CallOption) (*GetTagRsp, error)
	UpdateTag(ctx context.Context, in *UpdateTagReq, opts ...grpc.CallOption) (*UpdateTagRsp, error)
	CreateTag(ctx context.Context, in *CreateTagReq, opts ...grpc.CallOption) (*CreateTagRsp, error)
}

type blogStorageSvrClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogStorageSvrClient(cc grpc.ClientConnInterface) BlogStorageSvrClient {
	return &blogStorageSvrClient{cc}
}

func (c *blogStorageSvrClient) SelectCategoryList(ctx context.Context, in *SelectCategoryListReq, opts ...grpc.CallOption) (*SelectCategoryListRsp, error) {
	out := new(SelectCategoryListRsp)
	err := c.cc.Invoke(ctx, BlogStorageSvr_SelectCategoryList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogStorageSvrClient) GetCategory(ctx context.Context, in *GetCategoryReq, opts ...grpc.CallOption) (*GetCategoryRsp, error) {
	out := new(GetCategoryRsp)
	err := c.cc.Invoke(ctx, BlogStorageSvr_GetCategory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogStorageSvrClient) UpdateCategory(ctx context.Context, in *UpdateCategoryReq, opts ...grpc.CallOption) (*UpdateCategoryRsp, error) {
	out := new(UpdateCategoryRsp)
	err := c.cc.Invoke(ctx, BlogStorageSvr_UpdateCategory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogStorageSvrClient) CreateCategory(ctx context.Context, in *CreateCategoryReq, opts ...grpc.CallOption) (*CreateCategoryRsp, error) {
	out := new(CreateCategoryRsp)
	err := c.cc.Invoke(ctx, BlogStorageSvr_CreateCategory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogStorageSvrClient) SelectTagList(ctx context.Context, in *SelectTagListReq, opts ...grpc.CallOption) (*SelectTagListRsp, error) {
	out := new(SelectTagListRsp)
	err := c.cc.Invoke(ctx, BlogStorageSvr_SelectTagList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogStorageSvrClient) GetTag(ctx context.Context, in *GetTagReq, opts ...grpc.CallOption) (*GetTagRsp, error) {
	out := new(GetTagRsp)
	err := c.cc.Invoke(ctx, BlogStorageSvr_GetTag_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogStorageSvrClient) UpdateTag(ctx context.Context, in *UpdateTagReq, opts ...grpc.CallOption) (*UpdateTagRsp, error) {
	out := new(UpdateTagRsp)
	err := c.cc.Invoke(ctx, BlogStorageSvr_UpdateTag_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogStorageSvrClient) CreateTag(ctx context.Context, in *CreateTagReq, opts ...grpc.CallOption) (*CreateTagRsp, error) {
	out := new(CreateTagRsp)
	err := c.cc.Invoke(ctx, BlogStorageSvr_CreateTag_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogStorageSvrServer is the server API for BlogStorageSvr service.
// All implementations should embed UnimplementedBlogStorageSvrServer
// for forward compatibility
type BlogStorageSvrServer interface {
	SelectCategoryList(context.Context, *SelectCategoryListReq) (*SelectCategoryListRsp, error)
	GetCategory(context.Context, *GetCategoryReq) (*GetCategoryRsp, error)
	UpdateCategory(context.Context, *UpdateCategoryReq) (*UpdateCategoryRsp, error)
	CreateCategory(context.Context, *CreateCategoryReq) (*CreateCategoryRsp, error)
	SelectTagList(context.Context, *SelectTagListReq) (*SelectTagListRsp, error)
	GetTag(context.Context, *GetTagReq) (*GetTagRsp, error)
	UpdateTag(context.Context, *UpdateTagReq) (*UpdateTagRsp, error)
	CreateTag(context.Context, *CreateTagReq) (*CreateTagRsp, error)
}

// UnimplementedBlogStorageSvrServer should be embedded to have forward compatible implementations.
type UnimplementedBlogStorageSvrServer struct {
}

func (UnimplementedBlogStorageSvrServer) SelectCategoryList(context.Context, *SelectCategoryListReq) (*SelectCategoryListRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectCategoryList not implemented")
}
func (UnimplementedBlogStorageSvrServer) GetCategory(context.Context, *GetCategoryReq) (*GetCategoryRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategory not implemented")
}
func (UnimplementedBlogStorageSvrServer) UpdateCategory(context.Context, *UpdateCategoryReq) (*UpdateCategoryRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCategory not implemented")
}
func (UnimplementedBlogStorageSvrServer) CreateCategory(context.Context, *CreateCategoryReq) (*CreateCategoryRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedBlogStorageSvrServer) SelectTagList(context.Context, *SelectTagListReq) (*SelectTagListRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectTagList not implemented")
}
func (UnimplementedBlogStorageSvrServer) GetTag(context.Context, *GetTagReq) (*GetTagRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTag not implemented")
}
func (UnimplementedBlogStorageSvrServer) UpdateTag(context.Context, *UpdateTagReq) (*UpdateTagRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTag not implemented")
}
func (UnimplementedBlogStorageSvrServer) CreateTag(context.Context, *CreateTagReq) (*CreateTagRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTag not implemented")
}

// UnsafeBlogStorageSvrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlogStorageSvrServer will
// result in compilation errors.
type UnsafeBlogStorageSvrServer interface {
	mustEmbedUnimplementedBlogStorageSvrServer()
}

func RegisterBlogStorageSvrServer(s grpc.ServiceRegistrar, srv BlogStorageSvrServer) {
	s.RegisterService(&BlogStorageSvr_ServiceDesc, srv)
}

func _BlogStorageSvr_SelectCategoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectCategoryListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogStorageSvrServer).SelectCategoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogStorageSvr_SelectCategoryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogStorageSvrServer).SelectCategoryList(ctx, req.(*SelectCategoryListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogStorageSvr_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogStorageSvrServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogStorageSvr_GetCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogStorageSvrServer).GetCategory(ctx, req.(*GetCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogStorageSvr_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogStorageSvrServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogStorageSvr_UpdateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogStorageSvrServer).UpdateCategory(ctx, req.(*UpdateCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogStorageSvr_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogStorageSvrServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogStorageSvr_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogStorageSvrServer).CreateCategory(ctx, req.(*CreateCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogStorageSvr_SelectTagList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectTagListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogStorageSvrServer).SelectTagList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogStorageSvr_SelectTagList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogStorageSvrServer).SelectTagList(ctx, req.(*SelectTagListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogStorageSvr_GetTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogStorageSvrServer).GetTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogStorageSvr_GetTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogStorageSvrServer).GetTag(ctx, req.(*GetTagReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogStorageSvr_UpdateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogStorageSvrServer).UpdateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogStorageSvr_UpdateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogStorageSvrServer).UpdateTag(ctx, req.(*UpdateTagReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogStorageSvr_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogStorageSvrServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogStorageSvr_CreateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogStorageSvrServer).CreateTag(ctx, req.(*CreateTagReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BlogStorageSvr_ServiceDesc is the grpc.ServiceDesc for BlogStorageSvr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlogStorageSvr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blog_storage_svr.blog_storage_svr",
	HandlerType: (*BlogStorageSvrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectCategoryList",
			Handler:    _BlogStorageSvr_SelectCategoryList_Handler,
		},
		{
			MethodName: "GetCategory",
			Handler:    _BlogStorageSvr_GetCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _BlogStorageSvr_UpdateCategory_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _BlogStorageSvr_CreateCategory_Handler,
		},
		{
			MethodName: "SelectTagList",
			Handler:    _BlogStorageSvr_SelectTagList_Handler,
		},
		{
			MethodName: "GetTag",
			Handler:    _BlogStorageSvr_GetTag_Handler,
		},
		{
			MethodName: "UpdateTag",
			Handler:    _BlogStorageSvr_UpdateTag_Handler,
		},
		{
			MethodName: "CreateTag",
			Handler:    _BlogStorageSvr_CreateTag_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog_storage_svr.proto",
}
